In [1]:
# Part 1 - Data Preporcessing

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [34]:
# importing the dataset
df = pd.read_csv("Churn_Modelling.csv")

In [35]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [36]:
# Geography and Gender has categorial variables 
# Create dummy varibles
dummies = pd.get_dummies(data=df, columns=['Geography', 'Gender'], drop_first=True)

In [37]:

df = pd.concat([df, dummies], axis=1)

In [38]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  ...  Tenure    Balance  NumOfProducts  \
0       2       0.00              1  ...       2       0.00              1   
1       1   83807.86              1  ...       1   83807.86              1   
2       8  159660.80              3  ...       8  159660.80              3   
3       1       0.00              2  ...       1       0.00              2   
4       2  125510.82              1  ...       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary Exited  Geography_Germany  \
0          1               1        101348.88      1                  0   
1          0               1        112542.58      0                  0   
2          1               0        113931.57      1                  0   
3          0               0         93826.63      0                  0   
4          1               1         79084.10      0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0  

[5 rows x 29 columns]

In [39]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'RowNumber',
       'CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited', 'Geography_Germany', 'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [40]:
df = df.drop(['Geography', 'Gender'], axis=1)

In [41]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited', 'RowNumber', 'CustomerId', 'Surname',
       'CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [42]:
df = df.iloc[:, 13:27]

In [43]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited', 'Geography_Germany', 'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [44]:
# Matric of Features - which inclues the values without the headers!!
X = df.iloc[:, [2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13]].values

In [45]:
X

array([[619.,  42.,   2., ...,   0.,   0.,   0.],
       [608.,  41.,   1., ...,   0.,   1.,   0.],
       [502.,  42.,   8., ...,   0.,   0.,   0.],
       ...,
       [709.,  36.,   7., ...,   0.,   0.,   0.],
       [772.,  42.,   3., ...,   1.,   0.,   1.],
       [792.,  28.,   4., ...,   0.,   0.,   0.]])

In [46]:
Y = df.iloc[:, 10].values

In [47]:
Y

array([1, 0, 1, ..., 1, 1, 0])

In [48]:
# Splitting the data set into Test and Training sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [49]:
# We further need to apply feature scaling as ANN is very compute intensive exercise 
# It will help if all the variables are scaled.

In [50]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

In [51]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [52]:
# Part 2 - Building the model 

In [63]:
import keras

In [64]:
from keras.models import Sequential
from keras.layers import Dense

In [65]:
# Initialising the ANN

In [66]:
classifier = Sequential()

In [67]:
# Adding Input layers and First hidden layer

In [68]:
# We will choose the rectifier function for input layer and use the sigmoid activation function for output
# Unit = output_dim is the avy of inpur and output layers (11+1)/2 = 6

In [72]:
classifier.add(Dense(units= 6, activation = 'relu', input_dim = 11, kernel_initializer = 'uniform'))

In [73]:
# Adding Second hidden layer
classifier.add(Dense(units= 6, activation = 'relu', kernel_initializer = 'uniform'))

In [74]:
# Adding Output layer
classifier.add(Dense(units= 1, activation = 'sigmoid', kernel_initializer = 'uniform'))

In [75]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [76]:
# fitting the ANN to trainign set
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Use tf.cast instead.


/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/__main__.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  from ipykernel import kernelapp as app


Epoch 1/100
7500/7500 [==============================] - 2s 315us/step - loss: 0.4978 - acc: 0.7963
Epoch 2/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4310 - acc: 0.7963
Epoch 3/100
7500/7500 [==============================] - 1s 184us/step - loss: 0.4255 - acc: 0.7963
Epoch 4/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4215 - acc: 0.8095
Epoch 5/100
7500/7500 [==============================] - 1s 184us/step - loss: 0.4178 - acc: 0.8248
Epoch 6/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4156 - acc: 0.8296
Epoch 7/100
7500/7500 [==============================] - 1s 186us/step - loss: 0.4143 - acc: 0.8315
Epoch 8/100
7500/7500 [==============================] - 1s 185us/step - loss: 0.4131 - acc: 0.8313
Epoch 9/100
7500/7500 [==============================] - 1s 185us/step - loss: 0.4121 - acc: 0.8319
Epoch 10/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4110 - acc: 0.8315

7500/7500 [==============================] - 1s 184us/step - loss: 0.4016 - acc: 0.8353
Epoch 83/100
7500/7500 [==============================] - 1s 186us/step - loss: 0.4014 - acc: 0.8352
Epoch 84/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4017 - acc: 0.8331
Epoch 85/100
7500/7500 [==============================] - 1s 184us/step - loss: 0.4014 - acc: 0.8348
Epoch 86/100
7500/7500 [==============================] - 1s 183us/step - loss: 0.4015 - acc: 0.8344
Epoch 87/100
7500/7500 [==============================] - 1s 182us/step - loss: 0.4013 - acc: 0.8344
Epoch 88/100
7500/7500 [==============================] - 1s 185us/step - loss: 0.4018 - acc: 0.8359
Epoch 89/100
7500/7500 [==============================] - 1s 184us/step - loss: 0.4018 - acc: 0.8351
Epoch 90/100
7500/7500 [==============================] - 1s 185us/step - loss: 0.4015 - acc: 0.8345
Epoch 91/100
7500/7500 [==============================] - 1s 186us/step - loss: 0.4017 - acc: 0.8357
Epo

In [77]:
# Predict the test set results
y_pred = classifier.predict(X_test)

In [78]:
y_pred

array([[0.2420077 ],
       [0.4170385 ],
       [0.19671255],
       ...,
       [0.32357234],
       [0.33560506],
       [0.07055423]], dtype=float32)

In [85]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [86]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [87]:
cm

array([[1911,   80],
       [ 309,  200]])

In [88]:
Y_test.size

2500

In [89]:
accuracy = (1911+200)/2500

In [90]:
accuracy

0.8444